name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - development

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push GitHub
        uses: docker/build-push-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/ricardoalcantara/${{ github.event.repository.name }}:${{ steps.extract_branch.outputs.branch }}-latest
            ghcr.io/ricardoalcantara/${{ github.event.repository.name }}:${{ steps.extract_branch.outputs.branch }}-${{ steps.date.outputs.date }}

      - name: Login to PSCanary Container Registry
        if: github.ref == 'refs/heads/development'
        uses: docker/login-action@v2
        with:
          registry: registry.pscanary.com
          username: pscanary_dev
          password: ${{ secrets.PSCANARY_REGISTRY_PASSWORD }}

      - name: Build and Push PSCanary
        if: github.ref == 'refs/heads/development'
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            registry.pscanary.com/${{ github.event.repository.name }}:${{ steps.extract_branch.outputs.branch }}-latest
            registry.pscanary.com/${{ github.event.repository.name }}:${{ steps.extract_branch.outputs.branch }}-${{ steps.date.outputs.date }}
